# fly.toml app configuration file generated for starling-bank on 2025-06-19T14:17:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'starling-bank'
primary_region = 'phx'

[build]

[deploy]
release_command = "sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py create_admin'"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
