# Generated by Django 5.2.3 on 2025-06-22 01:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_add_frozenState'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aml_code',
            new_name='bic_code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='otp_code',
            new_name='tax_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tac_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vat_code',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic'),
        ),
    ]
