# Generated by Django 5.2.3 on 2025-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_rename_aml_code_userprofile_bic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_auth',
            field=models.CharField(blank=True, choices=[('enable', 'Enable'), ('disable', 'Disable')], default='disable', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='four_digit_auth_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
