# Generated by Django 5.2.3 on 2025-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_userprofile_two_factor_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='two_factor_auth',
            field=models.CharField(blank=True, choices=[('enable', 'Enable'), ('disable', 'Disable')], default='Enable', max_length=10),
        ),
    ]
