# Generated by Django 5.2.3 on 2025-08-09 05:25

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_userprofile_two_factor_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_application_fee_code',
            field=models.CharField(default=bank_app.models.generate_card_application_code, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
